org: jtsw1990
app: glimpse-lambda-process-data
service: lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
        - 'lambda:InvokeAsync'
      Resource: '*'

functions:
  process_data:
    handler: src.handler_process_data.process_data
    events:
      - s3:
          bucket: glimpse-landing-dev
          event: s3:ObjectCreated:*
          existing: true
  generate_image:
    handler: src.handler_image_gen.generate_image

custom:
  generate_image_trigger:
    handler: src.handler_process_data.process_data
    events:
      - invoke: generate_image
